// Product: 7
var products=[
    // Angular
     {show: "angular",
     title: "Angular Wall Art",
     description1: "Angular is an wall art product created through an experience in which the customer creates his own wall art combinations, with some paper, shaving cream, and acrylic painting of their choice. They just combine the shaving cream and the colors in the paper until they like the art created on it. Then it's just a matter of folding it and taking it to their homes.",
     cover: "../../imgs/Work/Product/Angular/angular1.jpg",
     imgs:["../../imgs/Work/Product/Angular/angular2.jpg", "../../imgs/Work/Product/Angular/angular3.jpg"],
     tools: ["Adobe Illustrator"],
     techniques:["Rapid Prototyping", "2D Sketching"],
     materials: ["Acrilic Paint", "Paper"],
     collab: ["Amanda Martínez", "Ana Julia Piña", "Jessica López", "Eloisa Tagle", "Alejandra De la Cuesta", "Andrea Flores", "Daniela García de Llano", "Alberto Velázquez", "Maria Fernanda Quiñones"]},
    // Aventurë
     {show: "aventure",
     title: "Aventurë Flashpacker Booklet",
     description1: "Aventurë is a pocket booklet for flashpackers, the new backpackers, designed with a hard cover in a way that protects the booklet through the user's trips. Its main function is to help you reconnect with yourself and your surroundings by facing several challenges, helping you to disconnect from things such as smart phones, technology and social media which won’t allow you to deeply appreciate your surroundings.",
     description2: "It is divided in 6 categories: Get Traditional, knowing the place as a native; Be Fearless, facing most common fears; Hungry, exploring local cuisine; Truth or Dare, facing awesome dares; Get Crazy, get out of your confort zone and do something crazy; Not Enough, random and fun activities",
     cover:"../../imgs/Work/Product/Aventure/aventure1.jpg",
     imgs:["../../imgs/Work/Product/Aventure/aventure2.jpg", "../../imgs/Work/Product/Aventure/aventure3.jpg", "../../imgs/Work/Product/Aventure/aventure4.jpg", "../../imgs/Work/Product/Aventure/aventure5.jpg"],
     tools: ["Adobe Illustrator"],
     techniques:["Rapid Prototyping", "Brainstorming", "2D Sketching"],
     materials: ["Paper", "Fabric", "Carton"],
     collab: ["Andrea Flores", "Dayan Blanco"]},
    // Dual
     {show: "dual",
     title: "Dual Flower Pot",
     description1: "Flower pot that is created from the need of people to feel company and that enjoy taking care of nature. Designed to fit in small places and work as a decoration element. Manufactured in 999 silver and tabeuia rosea wood with a forging system using nylamid molds and a round tip hammer.​​​​​​​ The wooden base comes with waterproof lacquer to provide stability and avoid scratches on the bottom.",
     description2: "Customized with the letters of the user’s choice, made with forging techniques. With an inner texture so that the soil won’t cause any scratches, so it looks new at all time. Molds and tools manufactured with CNC machining, used in the creation of the flower pot through forging techniques and the help of a hydraulic pressPreview in copper of the two halves of the pot before the welding process.",
     cover: "../../imgs/Work/Product/Dual/dual1.jpg",
     imgs:["../../imgs/Work/Product/Dual/dual2.jpg", "../../imgs/Work/Product/Dual/dual3.jpg", "../../imgs/Work/Product/Dual/dual4.jpg", "../../imgs/Work/Product/Dual/dual5.jpg", "../../imgs/Work/Product/Dual/dual6.jpg", "../../imgs/Work/Product/Dual/dual7.jpg"],
     tools: ["Autodesk Fusion360"],
     techniques:["Forging", "2D Sketching"],
     materials: ["Silver", "Wood"]},
    //  Neo
     {show: "neo",
     title: "Neo New-Nomads Collection",
     description1: "Ceramic and oak wood desk items collection for the neo nomads, young people between 20 and 30 years old, who are constantly traveling for either studies or work. Inspired in pure geometry, creating an interesting contrast between straight and organic lines.​​​​​​​",
     description2: "The first piece, a pen holder which can work as  a decorative element as well. The second piece, a card holder, in which the customer can store the designed cards, which use is to work as translator with the most basic phrases in 5 different languages. The final piece, a reminder, a geometric piece in which the customer can write a to do list.",
     cover: "../../imgs/Work/Product/Neo/neo1.jpg",
     imgs:["../../imgs/Work/Product/Neo/neo2.jpg", "../../imgs/Work/Product/Neo/neo3.jpg", "../../imgs/Work/Product/Neo/neo4.jpg"],
     tools: ["Solidworks"],
     techniques:["Rapid Prototyping", "2D Sketching", "CAD Modeling"],
     materials: ["Ceramic", "Wood"]},
    //  Pado
     {show: "pado",
     title: "Pado Furniture",
     description1: "Furniture made of poplar wood, gray melamine and satin glass. Thought for young people who want to save space Inspired in nature and the movement of water, for people who like nature but live in the city, to remind them about the pleasant nature contact experience.​​​​​​​ With its vertical form, its main function is to separate spaces in modern homes, which are increasingly smaller.",
     description2: "With three shelves made out of satin glass and gray melamine, ideal to have space to put your personal belongings. With a hidden trunk with bidimensional hinges and dampers to provide a smoother movement, ideal to save your personal belongings without looking messy.",
     cover:"../../imgs/Work/Product/Pado/pado1.jpg",
     imgs:["../../imgs/Work/Product/Pado/pado2.jpg", "../../imgs/Work/Product/Pado/pado3.jpg", "../../imgs/Work/Product/Pado/pado4.jpg", "../../imgs/Work/Product/Pado/pado5.jpg", "../../imgs/Work/Product/Pado/pado6.jpg"],
     tools: ["Autodesk Fusion360"],
     techniques:["Router CNC", "CAD Modeling", "Rendering"],
     materials: ["Melamine", "Glass", "Wood"],
     collab:["Karyna Ramirez"]},
    //  Dreams
     {show: "dreams",
     title: "Dreams, Food Design",
     description1: "There is a legend from the american tribes ojibwa and lacotas in which a spider woman who wove a net above the children’s cribs so that all evil would get tangled in it and won’t get to their dreams.",
     description2: "This same way, the abstraction of the spider woman guards the drink, the essence of the person who is about to drink it. The drink will be lighten on fire for a brief moment, pushing away all evil, in a purification ritual, allowing the user to taste the sweetness of the caramel that is on top of the structure. But nobody likes to wake up from a sweet dream, creating a sweet but bitter drink, since it is the bitterness of waking up from a sweet dream.",
     cover:"../../imgs/Work/Product/Dreams/dreams1.jpg",
     imgs:["../../imgs/Work/Product/Dreams/dreams2.jpg", "../../imgs/Work/Product/Dreams/dreams3.jpg", "../../imgs/Work/Product/Dreams/dreams4.jpg"],
     tools: ["Autodesk Fusion360", "Adobe Illustrator"],
     techniques:["CAD Modeling", "Laser Cut", "Router CNC"],
     materials: ["Acrylic", "Wood"]},
    //  Eternal
     {show: "eternal",
     title: "Eternal, Inclusive Design",
     description1: "Manufactured with Low Density Polyethylene (LDPE) and pine wood, Eternal (Eternos) is a product thought for people with Alzheimer, so that the family can keep stuff that reminds the customer of certain people, memories or places, in order to slow down the disease progression. Designed through an experience in which the Alzheimer customer will be able to directly interact in the manufacturing of its memory keeper, taking advantage of the affective memory which is the last one the patient will loose and slowing down the process by stimulating its memories with elements that remind him of people, moments and places.",
     description2: "The customer chooses the color of the LDPE he likes the most for the lid of its memory keeper. Afterwards, the plastic is melted along with wood chip and pressed with two iron molds and a hydraulic press. The extra material is removed with a Dremel tool, the piece is polished with sandpaper and the product is finally finished. The lid is put on top of the prefabricated in pine wood and is now ready to be taken home and keep memories for the customer. With a whole experience from start to end, it includes the packaging of the product with a little explanation card so that the user’s family know how the use of the product can help their loved one.",
     cover:"../../imgs/Work/Product/Eternal/eternal1.jpg",
     imgs:["../../imgs/Work/Product/Eternal/eternal2.jpg", "../../imgs/Work/Product/Eternal/eternal3.jpg", "../../imgs/Work/Product/Eternal/eternal4.jpg", "../../imgs/Work/Product/Eternal/eternal5.jpg"],
     tools: ["Rhinoceros", "Keyshot"],
     techniques:["Pressing", "Melting", "CAD Modeling", "2D Sketching", "Rendering"],
     materials: ["Wood", "Low Density Poliethylene"],
     collab: ["Andrea Flores", "Maria Fernanda Quiñones"]},
    ]

module.exports = products;